http:
  routers:
    backend:
      rule: "Host(`backend.example.com`)"
      service: backend
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver

    frontend:
      rule: "Host(`frontend.example.com`)"
      service: frontend
      entryPoints:
        - websecure
      tls:
        certResolver: myresolver

  services:
    backend:
      loadBalancer:
        servers:
          - url: "http://django_backend:8000"

    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:8080"
