# Generated by Django 5.1.2 on 2024-10-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(default="Uncategorized", max_length=100)),
                ("is_favorite", models.BooleanField(default=False)),
            ],
        ),
    ]
