# Generated by Django 4.2.16 on 2024-10-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="category",
            field=models.CharField(default="Uncategorized", max_length=100),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
